[package]
name = "file_upload"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.5"
actix-multipart = "0.6.1"
actix-web = "4.6.0"
tokio = "1.37.0"
futures-util = "0.3.30"
serde = { version = "1.0.202", features = ["derive"] }
mongodb = "2.8.2"
log = "0.4.21"
